baseURL = ""
languageCode = "en-us"
title = "theselfdrivingboat.com"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "theselfdrivingboat.com, we build self driving boats with solar panels to cross oceans"
    meta_og_title = "theselfdrivingboat.com"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = "theselfdrivingboat.com, we build self driving boats with solar panels to cross oceans"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Team"
    url = "https://www.notion.so/Team-607878500eec483db78e22ebdabc4069"
    weight = 1

[[menu.main]]
    name = "Roadmap"
    url = "https://www.notion.so/Roadmap-8470329b6be54f21b7b637fc7bf501b5"
    weight = 2

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#    weight = 3


[[menu.main]]
    name = "Early access"
    url = "https://docs.google.com/forms/d/e/1FAIpQLScwhMI642d3eFRBcGVUeF6Qi7bJYeN_lZo1Xwj9NgZkakl0Tw/viewform"
    weight = 3

#[[menu.main]]
#    name = "Contact"
#    url = "/contact/"
#    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

